export const USARI_IMAGES = {
  // Hero-level cinematic landscapes & wildlife
  giraffeHerd: '/images/usari/usari (91).jpg',
  giraffePortrait: '/images/usari/usari (20).jpg',
  giraffeGreen: '/images/usari/Usari (222).jpg',
  cheetahResting: '/images/usari/Usari (237).jpg',
  lionesses: '/images/usari/usari (100).JPG',
  lionessPortrait: '/images/usari/usari (102).JPG',
  lionCub: '/images/usari/Usari (245).jpg',
  sunsetPlain: '/images/usari/Usari (256).jpg',
  baboonPortrait: '/images/usari/usari (1).jpg',
  safariDetail: '/images/usari/usari (3).webp',
  impala: '/images/usari/Usari (222).jpg',
  greenWildlife: '/images/usari/usari (91).jpg',

  // Expanded gallery for redesign
  elephantsAtDusk: '/images/usari/Usari (220).jpg',
  zebraStripes: '/images/usari/Usari (221).jpg',
  savannahMist: '/images/usari/Usari (223).jpg',
  treeSilhouette: '/images/usari/Usari (224).jpg',
  safariSunrise: '/images/usari/Usari (225).jpg',
  acaciaLion: '/images/usari/Usari (226).jpg',
  migrationHerd: '/images/usari/Usari (227).jpg',
  tarangireElephants: '/images/usari/Usari (228).jpg',
  ngorongoroCrater: '/images/usari/Usari (229).jpg',
  serengetiHorizon: '/images/usari/Usari (230).jpg',
  leopardTree: '/images/usari/Usari (231).jpg',
  buffaloHerd: '/images/usari/Usari (232).jpg',
  maasaiSunset: '/images/usari/Usari (233).jpg',
  kilimanjaroPeak: '/images/usari/Usari (234).jpg',
  zanzibarBeach: '/images/usari/Usari (235).jpg',
  hadzabeHunters: '/images/usari/Usari (236).jpg',
  cheetahPortrait: '/images/usari/Usari (238).jpg',
  elephantFamily: '/images/usari/Usari (239).jpg',
  wildebeestCrossing: '/images/usari/Usari (240).jpg',
  hotAirBalloon: '/images/usari/Usari (241).jpg',
  lakeManyara: '/images/usari/Usari (242).jpg',
  flamingoLake: '/images/usari/Usari (243).jpg',
  walkingSafari: '/images/usari/Usari (244).jpg',
  campFire: '/images/usari/Usari (246).jpg',
  luxuryCamp: '/images/usari/Usari (247).jpg',
  mobileCamp: '/images/usari/Usari (248).jpg',
  guideBinoculars: '/images/usari/Usari (249).jpg',
  villageChildren: '/images/usari/Usari (250).jpg',
  coffeeFarm: '/images/usari/Usari (251).jpg',
  datogaBlacksmith: '/images/usari/Usari (252).jpg',
  chaggaCulture: '/images/usari/Usari (253).jpg',
  arushaTown: '/images/usari/Usari (254).jpg',
  rhinoNgorongoro: '/images/usari/Usari (255).jpg',

  // Authentic moments & detail shots
  giraffeCloseUp: '/images/usari/usari (20).jpeg',
  elephantMud: '/images/usari/usari (31).jpeg',
  lionRoar: '/images/usari/usari (5).jpeg',
  hippoPool: '/images/usari/usari (9).jpeg',
  cheetahGrass: '/images/usari/usari (10).jpeg',
  safariJeep: '/images/usari/usari (15).jpg',
  zebraDust: '/images/usari/usari (3).jpeg',
  wildbeestRiver: '/images/usari/usari (6).jpeg',
  birdWatcher: '/images/usari/usari (21).jpeg',
  goldenSavannah: '/images/usari/usari (30).jpeg',

  // Specific wildlife
  cheetahSide: '/images/Cheetah.jpg',
  cheetahWalk: '/images/Cheetah.jpeg',
  elephantHerd: '/images/Elephant.jpeg',
  elephantTwo: '/images/Elephant 2.jpeg',
  elephantThree: '/images/Elephant3.jpeg',
  leopard: '/images/Leopard.jpeg',
  lion: '/images/Lion.jpeg',
  lions: '/images/Lions.jpeg',
  zebra: '/images/Zebra.jpg',
  zebra2: '/images/Zebra2.jpeg',
  hippo: '/images/Hippopotamus.jpeg',
  hippo2: '/images/Hippopotamus2.jpeg',
  wildebeest: '/images/Wilderbeast.jpg',
  wildebeest2: '/images/Wilderbeast2.jpeg',
  wildebeest3: '/images/Wilderbeast3.jpeg',
  wildebeest4: '/images/Wilderbeast4.jpeg',
  giraffe: '/images/Girrafe.jpeg',
  antelope: '/images/Antelope.jpeg',
  antelope2: '/images/Antelop 2.jpeg',
  antelope3: '/images/Antelope 3.jpeg',
  maasai: '/images/Maasai.jpeg',
  yellowBilledStork: '/images/Yellow Billed Stork.jpeg',
  flamingo: '/images/Flamengo.jpeg',
  flamingo2: '/images/Flamengo2.jpeg',
  secretaryBird: '/images/Secretary Bird.jpeg',
  greyCrownedCrane: '/images/Grey Crowned Crane.jpeg',
  weaver: '/images/Weaver.jpeg',
  batEaredFox: '/images/Bat Eared Fox.jpeg',
  wildDog: '/images/Wild Dog.jpeg',
  crocodile: '/images/Crocodile.jpeg',
  blacksmithLapwing: '/images/Blacksmith Lapwing.jpeg',
  southernGroundHornbills: '/images/Southern Ground HornBills.jpeg',
  superbStarling: '/images/Supereb Sterling.jpeg',
  eagle: '/images/Eagle.jpeg',

  // Landscapes & culture
  kilimanjaro: '/images/Kilimanjaro.jpeg',
  mountMeru: '/images/Mount Meru.jpeg',
  lakeDuluti: '/images/lake duluti.jpeg',
  olduvaiGorge: '/images/Olduvai Gorge Sand.jpeg',
} as const;

export type UsariImageKey = keyof typeof USARI_IMAGES;

// Thematic sets for consistent section design
export const HERO_IMAGES = [
  USARI_IMAGES.sunsetPlain,
  USARI_IMAGES.giraffeHerd,
  USARI_IMAGES.lionesses,
  USARI_IMAGES.cheetahResting,
  USARI_IMAGES.ngorongoroCrater,
  USARI_IMAGES.kilimanjaroPeak,
  USARI_IMAGES.savannahMist,
  USARI_IMAGES.safariSunrise,
  USARI_IMAGES.acaciaLion,
] as const;

export const WILDLIFE_IMAGES = [
  USARI_IMAGES.lionesses,
  USARI_IMAGES.cheetahResting,
  USARI_IMAGES.elephantFamily,
  USARI_IMAGES.leopardTree,
  USARI_IMAGES.zebra,
  USARI_IMAGES.rhinoNgorongoro,
  USARI_IMAGES.buffaloHerd,
  USARI_IMAGES.elephantMud,
  USARI_IMAGES.lionRoar,
  USARI_IMAGES.hippoPool,
  USARI_IMAGES.cheetahGrass,
  USARI_IMAGES.wildDog,
  USARI_IMAGES.batEaredFox,
  USARI_IMAGES.crocodile,
] as const;

export const DESTINATION_IMAGES = [
  USARI_IMAGES.serengetiHorizon,
  USARI_IMAGES.ngorongoroCrater,
  USARI_IMAGES.kilimanjaroPeak,
  USARI_IMAGES.tarangireElephants,
  USARI_IMAGES.zanzibarBeach,
  USARI_IMAGES.lakeManyara,
  USARI_IMAGES.arushaTown,
  USARI_IMAGES.flamingoLake,
  USARI_IMAGES.migrationHerd,
] as const;

export const CULTURE_IMAGES = [
  USARI_IMAGES.maasaiSunset,
  USARI_IMAGES.hadzabeHunters,
  USARI_IMAGES.datogaBlacksmith,
  USARI_IMAGES.chaggaCulture,
  USARI_IMAGES.villageChildren,
  USARI_IMAGES.coffeeFarm,
] as const;

export const BIRD_IMAGES = [
  USARI_IMAGES.flamingo,
  USARI_IMAGES.flamingo2,
  USARI_IMAGES.secretaryBird,
  USARI_IMAGES.greyCrownedCrane,
  USARI_IMAGES.weaver,
  USARI_IMAGES.eagle,
  USARI_IMAGES.yellowBilledStork,
  USARI_IMAGES.southernGroundHornbills,
  USARI_IMAGES.superbStarling,
  USARI_IMAGES.blacksmithLapwing,
] as const;

export const CAMP_IMAGES = [
  USARI_IMAGES.luxuryCamp,
  USARI_IMAGES.mobileCamp,
  USARI_IMAGES.campFire,
  USARI_IMAGES.walkingSafari,
  USARI_IMAGES.guideBinoculars,
  USARI_IMAGES.safariJeep,
] as const;
