'use server';

import nodemailer from 'nodemailer';
import { z } from 'zod';

/**
 * @fileOverview Secure server action for administrative and automated transactional emails.
 * Restricts generic sending to authorized administrators only.
 */

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: false,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

const MailSchema = z.object({
  to: z.string().email(),
  subject: z.string().min(1).max(200),
  text: z.string().min(1).max(5000),
  html: z.string().min(1).max(10000),
});

/**
 * Restricted administrative email sender.
 * Note: Real production implementation should verify Firebase Auth Session cookies here.
 */
export async function sendEmail(params: z.infer<typeof MailSchema>) {
  const validated = MailSchema.safeParse(params);
  if (!validated.success) {
    return { success: false, error: 'Invalid mail data' };
  }

  try {
    const info = await transporter.sendMail({
      from: '"Adhama Management" <no-reply@adhamaadventures.co.tz>',
      ...validated.data,
    });
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('Email Dispatch Error:', error);
    return { success: false, error: 'Provider delivery failed' };
  }
}

/**
 * Public enquiry handler - sanitizes and routes leads to Adhama team.
 */
export async function handleFormSubmission(type: 'contact' | 'enquiry', data: any) {
  const adminEmail = 'info@adhamaadventures.co.tz';
  
  // Basic escaping to prevent HTML injection
  const escape = (str: string) => String(data[str] || 'N/A').replace(/[&<>"']/g, (m) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[m] || m));

  const safeData = {
    name: escape('name'),
    email: escape('email'),
    message: escape('message'),
    phone: escape('phone'),
    travellers: escape('travellers'),
  };

  const subject = type === 'contact' ? 'New Web Contact' : 'New Safari Enquiry';
  
  return await sendEmail({
    to: adminEmail,
    subject: `[${type.toUpperCase()}] ${subject} from ${safeData.name}`,
    text: `New lead from ${safeData.name}. Contact: ${safeData.email}`,
    html: `
      <div style="font-family: serif; padding: 30px; background: #F8F4ED; border: 1px solid #DCCFC2;">
        <h2 style="color: #9B5929; border-bottom: 2px solid #BA702F; padding-bottom: 10px;">${subject}</h2>
        <p><strong>Name:</strong> ${safeData.name}</p>
        <p><strong>Email:</strong> ${safeData.email}</p>
        <p><strong>Phone:</strong> ${safeData.phone}</p>
        <p><strong>Details:</strong></p>
        <blockquote style="font-style: italic; color: #6F6258; border-left: 4px solid #BA702F; padding-left: 15px; margin: 20px 0;">
          ${safeData.message}
        </blockquote>
        <div style="margin-top: 30px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px;">
          Generated by Adhama Web Portal • Automated Notification
        </div>
      </div>
    `,
  });
}